name: quiz_app CI/CD Pipeline

on:
  push:
    branches:
      - main     # Runs when pushing to main
  pull_request:
    branches:
      - main     # Runs on PRs targeting main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'   # Use your Flutter version
          channel: 'stable'

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Analyze code
      - name: Analyze
        run: flutter analyze

      # 5. Run tests
      - name: Run tests
        run: flutter test

      # 6. Build APK (Android)
      - name: Build APK
        run: flutter build apk --release

      # 7. Upload APK as Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
